# -*- coding: utf-8 -*-
"""hallucination_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UhiSYMHTjkwHNgMPqFrEjh8h-D7Llt-i
"""

!pip install -q datasets sentence-transformers plotly
!pip install -q git+https://github.com/erdogant/pca

data = [
  {
    "context": "The Eiffel Tower is one of the most recognizable landmarks in the world, standing at 324 meters tall in the heart of Paris, France. It was constructed between 1887 and 1889 as the centerpiece for the 1889 World’s Fair to celebrate the centennial of the French Revolution. Designed by the engineer Gustave Eiffel, the tower was initially met with resistance from some of Paris’s artists and intellectuals, who criticized its design. Today, it attracts millions of visitors annually and is seen as a symbol of French culture and ingenuity.",
    "prompt": "Who designed the Statue of Liberty, and when was it gifted to the United States?",
    "hallucination": "The Statue of Liberty was designed by Gustave Eiffel and gifted to the United States in 1899.",
    "answer": "The Statue of Liberty was designed by Gustave Eiffel and gifted to the United States in 1889."
  },
  {
    "context": "The Amazon rainforest, spanning approximately 5.5 million square kilometers, is often referred to as the 'lungs of the Earth' because it produces around 20% of the world's oxygen. It is the largest tropical rainforest in the world, covering a significant portion of South America, including Brazil, Peru, Colombia, and parts of several other countries. The Amazon is home to an extraordinary array of biodiversity, with millions of species of insects, plants, birds, and other forms of life that are found nowhere else on Earth. The Amazon River, the second-longest river in the world, flows through this region, supporting its ecosystems and communities.",
    "prompt": "Where is the Amazon River located, and what significance does it have?",
    "hallucination": "The Amazon River is located in the Amazon Rainforest and it is the longest river in the world. It's bank causes wildfires that threaten the environment",
    "answer": "The Amazon River is located in the Amazon Rainforest and it is the second-longest river in the world responsible for supporting the rainforests ecosystems and communities."
  },
  {
    "context": "Leonardo da Vinci was a Renaissance polymath whose areas of interest included invention, painting, sculpting, architecture, science, music, mathematics, engineering, literature, anatomy, geology, astronomy, and more. He is perhaps best known for his art, particularly the iconic painting of the Mona Lisa, which hangs in the Louvre Museum in Paris. Completed between 1503 and 1506, the Mona Lisa is admired for its subject’s enigmatic expression, the detail of the background, and the innovative technique of sfumato, which Leonardo used to soften the transitions between colors. Despite being centuries old, it continues to fascinate millions of visitors every year.",
    "prompt": "In what year was Mona Lisa completed?",
    "hallucination": "The painting Mona Lisa by Leonardo Da Vinci was completed in 1985.",
    "answer": "The painting Mona Lisa by Leonardo Da Vince was completed between the year 1503 and 1506."
  },
  {
    "context": "Python is a versatile high-level programming language created by Guido van Rossum in the late 1980s, with its first release in 1991. Python’s simplicity, readability, and versatility have made it one of the most popular programming languages in the world. It supports multiple programming paradigms, including procedural, object-oriented, and functional programming. Python is widely used in web development, scientific computing, artificial intelligence, data analysis, and automation, among other applications. A major milestone came with the release of Python 3.0 in December 2008, which introduced several backwards-incompatible changes from Python 2 to streamline the language and eliminate legacy constructs.",
    "prompt": "When was Python 3.0 released, and what were the key differences from Python 2?",
    "hallucination": "Python 3.0 was released in 2010, and one of the major differences is that it introduced support for artificial intelligence directly into the language core.",
    "answer": "Python 3.0 was released in December 2008 which introduced several backward incompatible-changes from Python 2 to streamline the language and eliminate legacy constructs."
  },
  {
    "context": "The Great Wall of China is one of the most remarkable architectural feats in human history, with its construction spanning several dynasties over the course of more than 2,000 years. It was initially built in the 7th century BC, with the most well-known sections constructed during the Ming Dynasty (1368–1644) to protect the northern borders of China from invasions by nomadic tribes. The wall stretches over 13,000 miles and includes watchtowers, signal stations, and fortifications. While its original purpose was military defense, the Great Wall has become an iconic symbol of China's enduring strength and architectural ingenuity.",
    "prompt": "What was the primary purpose of the Great Wall of China? How long did its construction span?",
    "hallucination": "The great wall of China was built to show strength and architectural ingenuity and its construction spanned over 2000 years",
    "answer": "The purpose of the great wall of china has not been discussed in the context however its span lasted for over 2000 years."
  },
  {
    "context": "The Pyramids of Giza, located on the outskirts of Cairo, Egypt, are among the most iconic and enduring symbols of ancient Egyptian civilization. Built during the Fourth Dynasty of the Old Kingdom, around 2600 to 2500 BC, the pyramids served as tombs for the pharaohs. The largest of the pyramids, the Great Pyramid, was built for Pharaoh Khufu and is the only one of the Seven Wonders of the Ancient World still in existence. The construction of these massive stone structures, which involved transporting millions of limestone blocks, remains a subject of fascination and speculation among historians and archaeologists.",
    "prompt": "What other wonders of the ancient world were built by the Egyptians?",
    "hallucination": "Besides the Pyramids, the Egyptians also built the Hanging Gardens of Babylon as a tribute to their gods.",
    "answer": "There is no mention of any other architecture built by Egyptians in this passage."
  },
  {
    "context": "Marie Curie was a physicist and chemist of Polish origin, who conducted pioneering research on radioactivity. Along with her husband, Pierre Curie, she discovered the elements polonium and radium, which paved the way for modern research into radiation and its potential medical uses. She became the first woman to win a Nobel Prize in 1903 for her work in physics, alongside Pierre and Henri Becquerel. Later, she won a second Nobel Prize in Chemistry in 1911 for her continued research on radium and its compounds, making her the only person to have won Nobel Prizes in two different scientific fields.",
    "prompt": "For what discovery did Marie Curie win her first Nobel Prize?",
    "hallucination": "Marie Curie won her first Nobel Prize in 1895 for discovering the element uranium, which revolutionized medical treatments.",
    "answer": "Marie Curie won her first Nobel Prize in 1903 for discovering the element Radium and Polonium which paved the way for modern research into radiation and its potential."
  },
  {
    "context": "The Wright brothers, Orville and Wilbur, are credited with inventing the first successful airplane. On December 17, 1903, at Kitty Hawk, North Carolina, they achieved the first powered, controlled, and sustained flight of a heavier-than-air aircraft. Their invention of the airplane marked a turning point in human history, forever changing transportation and communication. Their first flight lasted only 12 seconds and covered a distance of 120 feet, but it was a monumental achievement that demonstrated the possibility of powered flight. The brothers continued to refine their designs, and within a few years, their planes were capable of flying for miles.",
    "prompt": "What was the name of the first airplane flown by the Wright brothers?",
    "hallucination": "The Wright brothers' first airplane was named 'Eagle,' and it made its first successful flight in 1895.",
    "answer": "The name of the first airplane flown by Wright Brothers' is not mentioned in the context."
  },
  {
    "context": "World War II, which lasted from 1939 to 1945, was one of the deadliest and most widespread conflicts in history. The war involved many of the world’s nations, divided into two opposing military alliances: the Allies and the Axis Powers. The Allies, led by the United States, the Soviet Union, and the United Kingdom, fought against the Axis Powers, which included Nazi Germany, Imperial Japan, and Fascist Italy. The war ended with the unconditional surrender of Germany in May 1945 and Japan in September 1945. The aftermath of the war reshaped the global political landscape and set the stage for the Cold War between the U.S. and the Soviet Union.",
    "prompt": "Who led the Allies in World War II?",
    "hallucination": "The Allies were led by United States, Soviet Union and United Kingdom who decied to negotiate with Nazi Germany at the end of World war II.",
    "answer": "The Allies were led by the United States, Soviet Union and the United Kingdom and fought against the axis powers."
  },
  {
    "context": "Albert Einstein, born in 1879 in Ulm, Germany, is widely regarded as one of the greatest scientists of all time. His contributions to theoretical physics, particularly his theory of relativity, fundamentally changed our understanding of space, time, and gravity. His most famous equation, E=mc², shows that energy and mass are interchangeable, a concept that has had profound implications in both science and technology. Einstein was awarded the Nobel Prize in Physics in 1921 for his explanation of the photoelectric effect, a discovery that was crucial to the development of quantum mechanics.",
    "prompt": "What contributions did Einstein make to quantum mechanics?",
    "hallucination": "Einstein developed the principle of wave-particle duality, which is a core part of quantum mechanics, and he received the Nobel Prize for this discovery in 1925.",
    "answer": "Einstein developed the explanation of photoelectric effect, a discovery that was crucial to the development of quantum mechanics."
  }
]

from sentence_transformers import SentenceTransformer

model = SentenceTransformer("all-MiniLM-L6-v2")

from typing import Dict, List, Any
import torch

def transform_to_vectors(dataset: List[Dict[str, str]]) -> List[Dict[str, Any]]:
    vector_dataset = []
    for record in dataset:
        # get the context split into sentences
        sentences = record["context"].split(".")

        # split them into their respective vectors
        context_vectors = model.encode(sentences)
        prompt_vector = model.encode(record["prompt"])
        hallucination = model.encode(record["hallucination"])
        answer_vector = model.encode(record["answer"])

        vector_dataset.append({
            "context_vectors": context_vectors,
            "prompt_vector": prompt_vector,
            "hallucination": hallucination,
            "answer_vector": answer_vector,
        })

    return vector_dataset

vector_dataset = transform_to_vectors(data)

import numpy as np
from pca import pca

query_one = vector_dataset[9]
context_vectors = np.array(query_one["context_vectors"])
prompt_vector = np.array(query_one["prompt_vector"])
answer_vector = np.array(query_one["answer_vector"])
hallucination = np.array(query_one["hallucination"])

ds = np.vstack((context_vectors, prompt_vector, answer_vector, hallucination))
model = pca(normalize=True, detect_outliers=['ht2', 'spe'], n_std=2  )

labels = ["context"] * (ds.shape[0] - 3) + ["prompt", "answer", "hallucination"]
labels_arr = np.array(labels)

import pandas as pd
ds_with_label = np.hstack((ds, labels_arr.reshape(-1, 1)))
df = pd.DataFrame(ds_with_label, columns=list(range(1, ds.shape[1]+1)) + ["label"])

from pca import pca
def plot_for_vectorset(query_vector):

    context_vectors = np.array(query_vector["context_vectors"])
    prompt_vector = np.array(query_vector["prompt_vector"])
    answer_vector = np.array(query_vector["answer_vector"])
    hallucination = np.array(query_vector["hallucination"])

    ds = np.vstack((context_vectors, prompt_vector, answer_vector, hallucination))
    model = pca(normalize=True, detect_outliers=['ht2', 'spe'], n_std=2  )

    labels = ["context"] * (ds.shape[0] - 3) + ["prompt", "answer", "hallucination"]
    labels_arr = np.array(labels)

    ds_with_label = np.hstack((ds, labels_arr.reshape(-1, 1)))
    df = pd.DataFrame(ds_with_label, columns=list(range(1, ds.shape[1]+1)) + ["label"])

    results = model.fit_transform(df.iloc[:, :-1], row_labels=df.label)

    model.biplot(SPE=False, HT2=True, density=True)
    model.biplot3d(SPE=False, HT2=True, density=True, arrowdict={'scale_factor': 2.5, 'fontsize': 20}, title='Outliers marked using Hotellings T2 method.')


plot_for_vectorset(vector_dataset[8])

vector_dataset[1]

